### ISSUE TITLE
Use forEach?

### ISSUE THREAD

**Issue by ashaffer** [micro-js/reduce-array#1]
@queckezz Hey, glad you made this. I was thinking about making this myself yesterday.

Any thoughts on using [forEach](https://github.com/micro-js/foreach) so that this works on arrays and objects? It'd make it a bit bigger, but also more robust. Do you think it's worthwhile?

**Comment by queckezz** [comment]
We could also rename this one to `reduce-array`, use `foreach-array`, do the same for objects and then have a higher level wrapper which does just the type checking.

Overoptimization? I'd like to use just the basic `reduce-array` for that extra speed on performance critical stuff.

**Comment by ashaffer** [comment]
Ya, that's the other option. I think if we're going to create `reduce-array` and `reduce-obj`, they should probably not depend on the `foreach` implementations and just reproduce the iteration code themselves, for the small performance benefit. Any size reduction would be offset by the cost of the additional `require`'s probably.

I think that sounds good - rename this one to `reduce-array`, create a `reduce-obj` and then a bundled `reduce`.

**Comment by queckezz** [comment]
Agreed, I'll do that.
